<?php

/**
 * @file
 * Fastly module.
 */

/**
 * Implements hook_init().
 */
function fastly_init() {
  module_load_include('inc', 'fastly', 'fastly.api');
}

/**
 * Return permissions for the Fastly module.
 */
function fastly_permission() {
  $perms = array(
    'administer fastly' => array(
      'title' => t('Administer Fastly'),
      'description' => t('Allows users to administer Fastly.'),
      'restrict access' => TRUE,
    ),
  );

  return $perms;
}

/**
 * Implements hook_menu().
 */
function fastly_menu() {
  $items = array();

  $items['admin/config/services/fastly'] = array(
    'title' => 'fastly API',
    'description' => 'fastly Optimization',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fastly_setup_form'),
    'access arguments' => array('administer fastly'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Settings form.
 */
function fastly_setup_form($form_state) {
  $form['fastly_api_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Fastly API Key'),
    '#default_value' => variable_get('fastly_api_key', 'NONE'),
    '#description' => t('You can find it on your account settings page.'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}